// <auto-generated />
namespace estacionamentoApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class db290920191609 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db290920191609));
        
        string IMigrationMetadata.Id
        {
            get { return "201909291909462_db290920191609"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
