// <auto-generated />
namespace estacionamentoApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class dbFinal2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbFinal2));
        
        string IMigrationMetadata.Id
        {
            get { return "201910012246495_dbFinal2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
