// <auto-generated />
namespace estacionamentoApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class db2509191416 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db2509191416));
        
        string IMigrationMetadata.Id
        {
            get { return "201909251716333_db2509191416"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
